---
title: "Stat151A Lab 6"
output: html_document
date: "2024-02-21"
editor_options: 
  markdown: 
    wrap: 72
---

{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)

Distributions in R

Probability density functions

X: a random variable

p(x) : pdf of X

d___ : calclulates the pdf

{r}
# Evaluate the probability density function of each distribution
dnorm(1, mean = 0, sd = 1)  # normal distribution  
dexp(1.5, rate = 1)  # exponential distribution
dt(2, df = 5)  # t-distribution
dunif(0.3, min = 0, max = 1)  # uniform distribution
dbinom(2, size = 5, prob = 0.3)  # binomial distribution
dpois(1, lambda = 2)  # poisson distribution

Exercise 1

Plot the density function of the normal distribution whose mean is 2 and variance is 4.

{r}
x <- seq(-2,6,0.01)
pdf  <- dnorm(x,mean=2,sd=2)
plot(pdf)

cbind(x,pdf) %>% as.data.frame() %>% 
  ggplot() + 
    geom_point(aes(x=x,y=pdf))+ 
    theme_minimal()

Cumulative distribution functions

Recall that the cumulative distribution function of a random variable $X$ is $F(x) = \mathbb{P}(X \le x)$.

{r}
# Evaluate the cumulative density function of each distribution
pnorm(1, mean = 0, sd = 1)  # normal distribution  
pexp(1.5, rate = 1)  # exponential distribution
pt(2, df = 5)  # t-distribution
punif(0.3, min = 0, max = 1)  # uniform distribution
pbinom(2, size = 5, prob = 0.3)  # binomial distribution
pbinom(2.5, size = 5, prob = 0.3)  # binomial distribution
ppois(1, lambda = 2)  # poisson distribution
ppois(1.5, lambda = 2)  # poisson distribution

Exercise 2

Compute the following probabilities for $X \sim \text{Exp}(2)$. (1) $\mathbb{P}(X < 2)$ (2) $\mathbb{P}(X \le 2)$ (3) $\mathbb{P}(X > 1)$ (4) $\mathbb{P}(X \ge 1)$ (5) $\mathbb{P}(1 < X < 2)$ (6) $\mathbb{P}(1 \le X < 2)$

{r}
a <- pexp(2,2)
b <- pexp(2,2)
c <- 1-pexp(1,2)
d <- pexp(1,2,lower.tail=FALSE)
e <- pexp(2,2)-pexp(1,2)
f <- pexp(2,2)-pexp(1,2)

Exercise 3

Compute the following probabilities for $X \sim \text{Binomial}(8, 0.4)$. (1) $\mathbb{P}(X < 6)$ (2) $\mathbb{P}(X \le 6)$ (3) $\mathbb{P}(X > 3)$ (4) $\mathbb{P}(X \ge 3)$ (5) $\mathbb{P}(3 < X < 6)$ (6) $\mathbb{P}(3 \le X < 6)$

{r}
#this is discrete

a <- pbinom(5,8,0.4)
b <- pbinom(6,8,0.4)
c <- pbinom(2,8,0.4,lower.tail=FALSE)
d <- pbinom(3,8,0.4,lower.tail=FALSE)

#P(3<x<6) = P(3<X<=5)= P(X<=5) - P(X<=3)
e <- pbinom(5,8,0.4)- pbinom(3,8,0.4)

#P(3<=x<6) = P(3<X<=5)= P(X<=5) - P(X<3) = P(X<=5) - P(X<=2)
f <- pbinom(5,8,0.4)- pbinom(2,8,0.4)


Quantile functions

Recall that the quantile function $q_X$ of a random variable $X$ is defined as follows. For each $\alpha$, $$q_X(\alpha) = x$$ if $$P(X \le x) = \alpha.$$

{r}
# Evaluate the quantile function of each distribution
qnorm(0.05, mean = 0, sd = 1)  # normal distribution  
qexp(0.95, rate = 1)  # exponential distribution
qt(0.025, df = 5)  # t-distribution
qunif(0.1, min = 0, max = 1)  # uniform distribution

# The smallest value x s.t. F(x) >= p where F is the cdf
qbinom(0.3, size = 5, prob = 0.3)  # binomial distribution
qbinom(0.5, size = 5, prob = 0.3)  # binomial distribution
qpois(0.3, lambda = 2)  # poisson distribution
qpois(0.4, lambda = 2)  # poisson distribution

Exercise 4

Let $X$ be the exponential distribution whose rate parameter is 3 and $Y$ be the t-distribution whose degree of freedom is 5. Find $u$ in each case below. (1) $\mathbb{P}(X \le u) = 0.2$ (2) $\mathbb{P}(X \ge u) = 0.1$ (3) $\mathbb{P}(Y \le u) = 0.05$ (4) $\mathbb{P}(Y \ge u) = 0.3$ (5) $\mathbb{P}(-u \le Y \le u) = 0.9$ (6) $\mathbb{P}(0 \le Y \le u) = 0.3$

{r}
qexp(0.2,3)
qexp(1-0.1,3)
qt(0.05,5)
qt(1-0.3,5)

#P(-u<=Y<=u) = 1 - 2(P(Y<=-u)) = 0.9 -> P(Y<=-u) =0.05
-qt(0.05,5)

#P(0<=Y<=u) -> P(Y<=-u) =0.2
-qt(0.2,5)

Random sampling

{r}
set.seed(2024)
# Draw random samples from each distribution
rnorm(3, mean = 0, sd = 1)  # normal distribution  
rexp(2, rate = 1)  # exponential distribution
rt(5, df = 5)  # t-distribution
rbinom(4, size = 5, prob = 0.3)  # binomial distribution
rpois(2, lambda = 2)  # poisson distribution
runif(6, min = 0, max = 1)  # uniform distribution

Exercise 5

Draw 3000 samples from $\text{Binomial}(400, 0.1)$ and plot a histogram of samples in a density scale. Compare it with the probability density function of $N(40, 6^2)$.

{r}
set.seed(1234)
a <- rbinom(3000, 400, 0.1)

b <- seq(20, 60, 0.05)
y <- dnorm(b, 40, 6)

data.frame(a) %>%
  ggplot() +
  geom_histogram(aes(x = a), bins = 20, fill = "lightblue", color = "black", alpha = 0.7) +
  geom_line(data = data.frame(b, y), aes(x = b, y = y), color = "red", size = 1) +
  labs(title = "Histogram of a (Binomial Distribution) with Overlayed Normal Distribution",
       x = "Values of a",
       y = "Frequency / Density")


Exercise 6

Let $X$ be the standard normal distribution. Estimate the value of $\mathbb{E}[X^4]$ by drawing samples from the distribution.

{r}
# Leave your answer below
b <- rnorm(100000,0,1)
ans <- mean(b^4)

